### ISSUE TITLE
feeluown:  called with unexpected argument 'extraEntries'

### ISSUE THREAD

**Issue by wineee** [berberman/flakes#24]
error: anonymous function at /nix/store/c2kq57hv8hlnv43x5yvf64drfix1bnhq-source/pkgs/build-support/make-desktopitem/default.nix:7:1 called with unexpected argument 'extraEntries'

       at /nix/store/k784x005a2xky3r6zl7nhg596ydyz8gv-source/packages/feeluown/default.nix:6:13:

            5|   inherit (pythonPackages) python wrapPython;
            6|   desktop = makeDesktopItem rec {
             |             ^
            7|     name = "FeelUOwn";
(use '--show-trace' to show detailed location information)

**Comment by berberman** [comment]
Caused by the [upstream change](https://github.com/NixOS/nixpkgs/commit/0c713dbed40dd87090a4632cffc7b088653f35cb) ([release note](https://github.com/NixOS/nixpkgs/commit/066a581a80c0939423ff8b2d4b451a07ea8e5865)) of `makeDesktopItem`, pr is welcome!

**Comment by wineee** [comment]
~> nix flake show
git+file:///home/rewine/dde/flakes-1?ref=master&rev=98f8f4c632942062226f0c50e1aa29c3958eb0cc&shallow=1
├───apps
│   └───x86_64-linux
error: not an app definition


How to compile natively？

**Comment by berberman** [comment]
I think you can use `nix build .#feeluown` to build that drv.
